CREATE TABLE IF NOT EXISTS categories (
  category_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  category_name VARCHAR(255) NOT NULL,
  CONSTRAINT uq_categories_name UNIQUE (category_name)
);