CREATE TABLE IF NOT EXISTS endpointhit (
  endpointhit_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  endpointhit_app VARCHAR(255) NOT NULL,
  endpointhit_uri VARCHAR(255) NOT NULL,
  endpointhit_ip VARCHAR(255) NOT NULL,
  endpointhit_timestamp timestamp NOT NULL
);